export const profiles = [
  {
    id: 0,
    img: "src/assets/1st image.png",
    name: "Joycelyn",
    age: 25,
    email: "joycelyn@example.com",
    btnText: "Click me!",
  },
  {
    id: 1,
    img: "src/assets/2nd image.png",
    name: "Martin",
    age: 22,
    email: "martin@example.com",
    btnText: "Click me!",
  },
  {
    id: 2,
    img: "src/assets/3rd image.png",
    name: "Jordyn",
    age: 24,
    email: "jordyn@example.com",
    btnText: "Click me!",
  },
  {
    id: 3,
    img: "src/assets/4th image.png",
    name: "Leo",
    age: 25,
    email: "leo@example.com",
    btnText: "Click me!",
  },
  {
    id: 4,
    img: "src/assets/5th image.png",
    name: "Marilyn",
    age: 30,
    email: "marilyn@example.com",
    btnText: "Click me!",
  },
  {
    id: 5,
    img: "src/assets/6th image.png",
    name: "Lindsey",
    age: 26,
    email: "lindsey@example.com",
    btnText: "Click me!",
  },
  {
    id: 6,
    img: "src/assets/7th image.png",
    name: "Dias",
    age: 27,
    email: "dias@example.com",
    btnText: "Click me!",
  },
  {
    id: 7,
    img: "src/assets/8th image.png",
    name: "Ryan",
    age: 28,
    email: "ryan@example.com",
    btnText: "Click me!",
  },
];
